name: Update README

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update this repo's README with recent activity
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update README with recent activity
        uses: jamesgeorge007/github-activity-readme@master
        with:
          commit_message: "🤖 Update README with recent activity"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
